#!/usr/bin/env bash
# Generated by mutator-guard deploy.sh on $(node -e 'process.stdout.write(new Date().toISOString())').
# Do not edit — overwritten on next deploy. Sibling: pi-curator. Language: typescript.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SIBLING_ROOT="$(cd "$HERE/../.." && pwd)"
MUTATOR_GUARD_ROOT="${MUTATOR_GUARD_ROOT:-}"

if [[ -z "$MUTATOR_GUARD_ROOT" ]]; then
  echo "MUTATOR_GUARD_ROOT env var required (path to mutator-guard checkout)" >&2
  exit 2
fi

# SAFETY.ack gate.
if [[ ! -f "$SIBLING_ROOT/.mutator-rules/SAFETY.ack" ]]; then
  echo "missing $SIBLING_ROOT/.mutator-rules/SAFETY.ack — run mg-ack-safety.sh first" >&2
  exit 2
fi

# Re-compute composite hash from deployed files and compare against .mutator-sha.
COMPUTED_SHA="$(cat "$HERE/stryker.config.json" "$HERE/run.sh" "$HERE/vitest.mutation.config.ts" "$HERE/provenance.json" 2>/dev/null | sha256sum | awk '{print $1}')"
ACTUAL_SHA="$(cat "$SIBLING_ROOT/.mutator-rules/.mutator-sha" 2>/dev/null || echo "")"
if [[ "$COMPUTED_SHA" != "$ACTUAL_SHA" ]]; then
  echo "sha mismatch: deployed files tampered or stale (re-run deploy.sh)" >&2
  echo "  expected: $ACTUAL_SHA" >&2
  echo "  computed: $COMPUTED_SHA" >&2
  exit 2
fi

cd "$SIBLING_ROOT"
exec node "$MUTATOR_GUARD_ROOT/node_modules/@stryker-mutator/core/bin/stryker.js" run "$HERE/stryker.config.json"
