// vitest.mutation.config.ts — GENERATED by mutator-guard. Do NOT edit.
// Changes will be overwritten on next deploy.
// Mirrors pi-curator's root vitest.config.ts (include: src/**/*.test.ts, node env).
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['src/**/*.test.ts'],
    globals: false,
    environment: 'node',
  },
});
